name: Generate Contribution Snake

on:
  schedule:
    # Run automatically every day at midnight UTC
    - cron: "0 0 * * *"

  # Allow the workflow to be started manually
  workflow_dispatch:

  # Run when changes are pushed to main
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Generate contribution snake
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: BOW4LE

          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Publish contribution snake
        uses: crazy-max/ghaction-github-pages@v4
        with:
          build_dir: dist
          branch: output

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
